POST http://localhost:3001/api/materials
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name"

Material test
--boundary
Content-Disposition: form-data; name="description"

Material test description
--boundary
Content-Disposition: form-data; name="user_id"

101
--boundary
Content-Disposition: form-data; name="visible"

true
--boundary
Content-Disposition: form-data; name="is_url"

true
--boundary
Content-Disposition: form-data; name="url"

https://www.google.com
--boundary
Content-Disposition: form-data; name="tagIds"

[2, 36]
--boundary--